version: "3.9"

services:
  postgresdb:
    image: postgres:17.5-alpine
    container_name: wise_educ_postgres_db
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASS}
    ports:
      - 5432:5432
    volumes:
      - postgres-data:/var/lib/postgresql/data
  # elasticsearch:
  #   image: elasticsearch:8.12.2
  #   container_name: elasticsearch
  #   ports:
  #     - 9200:9200
  #   volumes:
  #     - es-data:/usr/share/elasticsearch/data
  #   environment:
  #     - bootstrap.memory_lock=true
  #     - discovery.type=single-node
  #     - "ES_JAVA_OPTS=-Xms2g -Xmx2g"
  #     - xpack.security.enabled="false"
  #     # - ELASTIC_PASSWORD=$ELASTIC_PASSWORD
  #   ulimits:
  #     memlock:
  #       soft: -1
  #       hard: -1
  # kibana:
  #   image: docker.elastic.co/kibana/kibana:8.12.2
  #   ports:
  #     - "5601:5601"
  #   environment:
  #     ELASTICSEARCH_URL: http://elasticsearch:9200
  #   depends_on:
  #     - elasticsearch
  # web:
  #   build: .
  #   command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
  #   environment:
  #     - RAILS_MASTER_KEY=${RAILS_MASTER_KEY}
  #   volumes:
  #     - .:/wise_educ
  #   ports:
  #     - "3000:3000"
  #   depends_on:
  #     - postgresdb
  # - elasticsearch
  # minio:
  #   image: minio/minio:RELEASE.2024-03-10T02-53-48Z
  #   container_name: minio
  #   ports:
  #     - 9000:9000
  #     - 9001:9001

  #   volumes:
  #     - minio-data:/data
  #   environment:
  #     MINIO_ROOT_USER: ${MINIO_ACCESS_KEY}
  #     MINIO_ROOT_PASSWORD: ${MINIO_SECRET_KEY}
  #     MINIO_MEDIA_STORE_BUCKET: ${MINIO_MEDIA_STORE_BUCKET}
  #   command: server --console-address :9001 /data
volumes:
  postgres-data:
  es-data:
  minio-data:
