default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: <%= ENV.fetch("DB_HOST") { "localhost" } %>
  port: <%= ENV.fetch("DB_PORT") { "5432" } %>
  username: <%= ENV.fetch("DB_USERNAME") { "postgres" } %>
  password: <%= ENV.fetch("DB_PASS") { "postgres" } %>

development:
  <<: *default
  database: <%= ENV.fetch("DB_NAME") { "wise_educ_development" } %>

test:
  <<: *default
  database: <%= ENV.fetch("DB_NAME") { "wise_educ_test" } %>

production:
  <<: *default
  database: <%= ENV.fetch("DB_NAME_PROD") { "wise_educ_production" } %>
  username: <%= ENV['DB_USERNAME_PROD'] %>
  password: <%= ENV['DB_PASS_PROD'] %>
